version: '3.8'

services:
  redis-bot:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - my_network
  fastapi:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./repository:/app/repository
      - ./utils:/app/utils
      - ./database.py:/app/database.py
      - ./app.db:/app/app.db
    depends_on:
      - bot
    networks:
      - my_network

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    container_name: telegram_bot
    ports:
      - "8443:8443"
    volumes:
      - ./models:/bot/models
      - ./repository:/bot/repository
      - ./utils:/bot/utils
      - ./database.py:/bot/database.py
      - ./app.db:/bot/app.db
      - ./media:/bot/media
    networks:
      - my_network
  celery-worker:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    container_name: celery_worker
    command: celery -A tasks.app worker -B --loglevel=info
    volumes:
      - ./models:/bot/models
      - ./repository:/bot/repository
      - ./utils:/bot/utils
      - ./database.py:/bot/database.py
      - ./app.db:/bot/app.db
    networks:
      - my_network
    depends_on:
      - redis-bot
      - bot
      - fastapi
networks:
  my_network:
    driver: bridge